# Generated by Django 5.0.14 on 2026-07-18 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('kader_nakes', 'Kader/Nakes'), ('orangtua', 'Orang Tua')], default='orangtua', max_length=20),
        ),
    ]
