# Generated by Django 5.0.14 on 2026-07-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_seed_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='posyandu_location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
