# Generated by Django 5.0.14 on 2026-07-13 15:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('male', 'Laki-laki'), ('female', 'Perempuan')], max_length=10)),
                ('exclusive_breastfeeding', models.BooleanField(blank=True, null=True)),
                ('birth_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GrowthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('measured_at', models.DateField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('age_months', models.PositiveIntegerField(help_text='Usia anak saat pengukuran, dalam bulan')),
                ('height_for_age_z', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_for_height_z', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('risk_status', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_records', to='growth.child')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_growth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['age_months'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_status', models.CharField(max_length=10)),
                ('reason_codes', models.JSONField(default=list)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='growth.child')),
            ],
            options={
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='growthrecord',
            constraint=models.UniqueConstraint(fields=('child', 'measured_at'), name='unique_measurement_per_day'),
        ),
    ]
