# Generated by Django 5.0.14 on 2026-07-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthrecord',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Catatan tambahan dari kader/nakes saat pengukuran'),
        ),
    ]
