# Generated by Django 5.0.14 on 2026-07-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0002_growthrecord_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthrecord',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Lokasi pengukuran, mis. Posyandu Melati / Klinik Sehat', max_length=150),
        ),
        migrations.AddField(
            model_name='growthrecord',
            name='officer_name',
            field=models.CharField(blank=True, default='', help_text='Nama petugas yang melakukan pengukuran', max_length=150),
        ),
    ]
