# Generated by Django 5.0.14 on 2026-07-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0003_growthrecord_location_growthrecord_officer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthrecord',
            name='clean_water_access',
            field=models.BooleanField(blank=True, help_text='Akses air bersih & sanitasi layak', null=True),
        ),
        migrations.AddField(
            model_name='growthrecord',
            name='immunization_complete',
            field=models.BooleanField(blank=True, help_text='Imunisasi lengkap sesuai usia', null=True),
        ),
        migrations.AddField(
            model_name='growthrecord',
            name='recurrent_illness',
            field=models.BooleanField(blank=True, help_text='Riwayat sakit/diare berulang dalam 3 bulan terakhir', null=True),
        ),
    ]
