# Generated by Django 5.0.14 on 2026-07-17 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0004_growthrecord_clean_water_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthrecord',
            name='weight_for_age_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
