# Generated by Django 5.0.14 on 2026-07-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0005_growthrecord_weight_for_age_z'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='birth_length_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='gestational_age_weeks',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Usia kehamilan saat lahir, dalam minggu — indikator prematuritas', null=True),
        ),
        migrations.AddField(
            model_name='child',
            name='parent_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='child',
            name='parent_occupation',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='growthrecord',
            name='head_circumference_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Lingkar kepala — opsional, standar WHO Head-Circumference-for-Age, indikator tambahan mikrosefali', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='growthrecord',
            name='head_circumference_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='recommendations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='score',
            field=models.PositiveSmallIntegerField(default=0, help_text='0-100, higher = more severe'),
        ),
    ]
