# Generated by Django 5.0.14 on 2026-07-17 13:20
"""
Backfill for the 3-tier -> 4-tier risk_status change (normal/watch/risk ->
normal/berisiko/stunting/malnutrisi, see services/risk_engine.py).

GrowthRecord.risk_status is a live-computed field (recomputed on every
create/update), so existing rows are recomputed here from their already-
stored real WHO Z-scores (height_for_age_z/weight_for_height_z/
weight_for_age_z) via the new score_risk() — head_circumference_z is None
for every pre-existing row since that field didn't exist yet, which
score_risk() already handles as "no HCZ contribution".

RiskAssessment.risk_status is a point-in-time audit log, not a live status,
so historical rows are only label-remapped (watch->berisiko, risk->
malnutrisi) rather than recomputed — recomputing would fabricate a more
precise historical judgement than was actually made at that time.
"""
from django.db import migrations

# Imported directly rather than re-deriving the formula here: this is a
# one-off backfill tied to the exact score_risk() shipped alongside this
# migration, not a permanently-frozen historical snapshot.
from apps.growth.services.risk_engine import score_risk


def recompute_growth_record_status(apps, schema_editor):
    GrowthRecord = apps.get_model('growth', 'GrowthRecord')
    for record in GrowthRecord.objects.exclude(height_for_age_z=None).iterator():
        result = score_risk(
            haz=float(record.height_for_age_z),
            whz=float(record.weight_for_height_z) if record.weight_for_height_z is not None else 0.0,
            waz=float(record.weight_for_age_z) if record.weight_for_age_z is not None else 0.0,
            hcz=None,
        )
        record.risk_status = result.risk_status
        record.save(update_fields=['risk_status'])


def remap_risk_assessment_status(apps, schema_editor):
    RiskAssessment = apps.get_model('growth', 'RiskAssessment')
    RiskAssessment.objects.filter(risk_status='watch').update(risk_status='berisiko')
    RiskAssessment.objects.filter(risk_status='risk').update(risk_status='malnutrisi')


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0006_child_birth_length_cm_child_gestational_age_weeks_and_more'),
    ]

    operations = [
        migrations.RunPython(recompute_growth_record_status, migrations.RunPython.noop),
        migrations.RunPython(remap_risk_assessment_status, migrations.RunPython.noop),
    ]
