# Generated by Django 5.0.14 on 2026-07-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0008_posyanduschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthrecord',
            name='photo',
            field=models.ImageField(blank=True, help_text='Foto balita opsional — dokumentasi pertumbuhan, bukan input AI-vision', null=True, upload_to='growth_photos/%Y/%m/'),
        ),
    ]
