# Generated by Django 5.0.14 on 2026-07-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0009_growthrecord_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='posyandu_location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
