# Generated by Django 5.0.14 on 2026-07-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('growth', '0012_backfill_link_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='public_token',
            field=models.CharField(blank=True, editable=False, max_length=48, null=True, unique=True),
        ),
    ]
